--학생테이블
CREATE TABLE STUDENT (
	SNO INT NOT NULL COMMENT '학번',
	SNAME varchar(20) NULL COMMENT '이름',
	SGRADE INT NULL COMMENT '학년',
	SCLASS CHAR NULL COMMENT '반',
	CONSTRAINT class_pk PRIMARY KEY (SNO)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='학생테이블';

-- 출석테이블
CREATE TABLE attendance (
	SNO INT NULL COMMENT '학번',
	ATND_YN CHAR(1) NULL COMMENT '출석여부',
	ATND_DATE varchar(10) NULL COMMENT '출석일'
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='출석테이블';

-- 학생데이터

INSERT INTO student (SNO, SNAME, SGRADE, SCLASS) VALUES(1, '홍길동', 1, 'A');

INSERT INTO student (SNO, SNAME, SGRADE, SCLASS) VALUES(2, '임꺽정', 2, 'B');

INSERT INTO student (SNO, SNAME, SGRADE, SCLASS) VALUES(3, '김동현', 3, 'A');

INSERT INTO student (SNO, SNAME, SGRADE, SCLASS) VALUES(4, '손흥민', 1, 'A');

INSERT INTO student (SNO, SNAME, SGRADE, SCLASS) VALUES(5, '이강인', 2, 'A');

INSERT INTO student (SNO, SNAME, SGRADE, SCLASS) VALUES(6, '황희철', 1, 'A');